INSERT INTO `skills`(`id`,`title`,`about`,`desc`,`name`,`color`) VALUES (1,'Php','I''m keeping to enhance my own PHP framework with Model-View-Control modulation. 
 <br /> You also can get acquainted with him and fork in the follow GitHub repository. 
 <br/ >For instance, this framework entirely is building in the Dependency Injection and you may use it however you want. 
 <br /> In the further, I''m looking to write own artisan for migrations/seeds creating, cause it''s being one is the most easy and rapid way to implement it.
 </br> From the Front Side, I want to integrate it with Vue.js and Webpack compiler for Vue.js; I would like to notice a several things, which are emphasizing this project at the whole: 
 <br/ > <div class=''ui list''> <a class=''item'' href=''javascript:;''> It''s being an entirely free, and you can just clone it. </a> 
 <a class=''item'' href=''javascript:;''> All of your project is not restricted by anything, you can implement and enhance him in the future , accordingly to your requirements or something like that. 
 </a> <a class=''item'' href=''javascript:;''> This project is building onto PDO connection, with Singleton pattern, so, at the whole, it will eliminate any ways to connect to Database a plenty times. 
 </a> <a class=''item'' href=''javascript:;''> You also can register and develop your API or use this framework as RestApi for your project purposes, you''re just demanding to put your routes in the essential folder, and keep to create some outstanding! 
</a> <a link=''javascript:;'' class=''item''>This framework is powered by ActiveRecord for database connection, definitely. 
 </a> </div> <br/>You can just check out my repository allow to get more acquainted with it I''m also having another repositories, which are related with PHP, like API connection and so on. 
 <br />I''m actively working with PHP now, and looking for objective programming, trying to adhere to the SOLID principles. 
 <br /> Also I had an experience in the parsing with PHP. <br /> <a href=''https://github.com/Emik123dsa/BroomMVC'' rel=''_target'' > <i class=''github icon''> </i> Follow me!</a>','I''m actively engaging in the PHP, also have an experience with Model-View-Controller modulation, PDO Connection, and more oriented on the Objective programming, interacted with standard patterns as ''Singleton'', ''Many to Many''','php','blue');
INSERT INTO `skills`(`id`,`title`,`about`,`desc`,`name`,`color`) VALUES (2,'JavaScript','JS about','I prefer to programming on native JavaScript for finding any solutions','js','yellow');
INSERT INTO `skills`(`id`,`title`,`about`,`desc`,`name`,`color`) VALUES (3,'Laravel','I''m currently using a Laravel for my essential projects deploying, at the first time, Laravel is being sufficient boon framework for small and immense projects, like for instance, I can quickly use it with Laravel Mix, simultaneously, Webpack plugins/ Vue.js / React and so on. <br />Also Laravel can give you an opportunity to use integrated artisan commander. <br /> You can create your own MVC model in a several steps and functionally use it in the further. <br /> You also can check out my github repository with standard CRUD operations. <br/ > By the way, this project is powered by Laravel! <div class=''ui list''> <div class=''item''> <i class=''large github middle aligned icon''></i> <div class=''content''><a class=''header'' href=''https://github.com/Emik123dsa/TodoVue'' rel=''_target''> My TodoVue project </a></div></div></div>','Laravel is being sufficient wonderful framework for rapid projects building, essentially, working with php artisan is increasing your velocity potential. Like you can just create any migrations, model, view, collection, seed and so on','laravel','red');
INSERT INTO `skills`(`id`,`title`,`about`,`desc`,`name`,`color`) VALUES (4,'Docker','I''m usually using Docker for my little projects, you can create your working server just in a several steps: install Nginx, Php-fpm or Node-js, as database you may use MySql, PostgreSql and etc. For instance, this code essential determine all of the required services for your server working: <br /> <div class=''ui segment placeholder''><div class=''ui list''> <div class=''item''><i class=''folder blue icon''></i><div class=''content''><div class=''header''>docker</div><div class=''description''>Docker Fpm and Nginx building settings</div><div class=''list''><div class=''item''><i class=''docker blue icon''></i><div class=''content''><div class=''header''>Nginx.Dockerfile</div><div class=''description''>Nginx</div></div></div><div class=''item''><i class=''docker blue icon''></i><div class=''content''><div class=''header''>Fpm.Dockerfile</div><div class=''description''>PHP-FPM</div></div> </div><div class=''item''> <i class=''folder blue icon''> </i> <div class=''content''> <div class=''header''>conf</div>  <div class=''description''> <div class=''list''> <div class=''item''> <i class=''settings icon''> </i> <div class=''content''> <div class=''header''> vhost.conf </div> <div class=''description''> Settings default Nginx</div> </div> </div></div> </div> </div></div></div></div></div><div class=''item''><i class=''docker red icon''></i> <div class=''content''> <div class=''header''>docker-compose.yml</div> <div class=''description''>Determine all of the required plugins</div></div> </div></div> </div>','I also prefer to deploy my projects via Docker compilation, cause it''s making total process of installation indeed quickly and high productive, without any struggles','docker','blue');
INSERT INTO `skills`(`id`,`title`,`about`,`desc`,`name`,`color`) VALUES (5,'Node-js','Currently, I''m also looking for Node-js Back-End development. From one side, is giving also a plenty of opportunities to create something outstanding. I would like to say that you can build your project essentially with Express web-server, involve Mongoose as MongoDB server database, instead of standard MySql, PostgreSql. <br /> I''m trying to enhance myself in these realms and having large desire to get started own projects with JS Back-End Server-Side-Rendering.','I''m actively studying a Node.js, Express, MongoDb as Back End projects building','node-js','olive');
INSERT INTO `skills`(`id`,`title`,`about`,`desc`,`name`,`color`) VALUES (6,'Database','Database about','I''m acquainted with MySql stadard functions, migrations','database','pink');
INSERT INTO `skills`(`id`,`title`,`about`,`desc`,`name`,`color`) VALUES (7,'Vue-js','Vue-js about','I''m actively studying Vuex (actions, mutations, store, getters), Nuxt.js as Server Side Rendering, Vue-Cli, Vue, VueAxios, VueRouters and a lot of plugins for deploying','vue-js','green');
INSERT INTO `skills`(`id`,`title`,`about`,`desc`,`name`,`color`) VALUES (8,'Webpack','Webpack about','I''m also actively using Webpack for any projects building, for instance, you can indeed easy compile any required files to one JS with Babel helping, you might check it out beneath:','webpack','blue');
INSERT INTO `skills`(`id`,`title`,`about`,`desc`,`name`,`color`) VALUES (9,'CSS3','CSS3 about','Obviously, it''s being the most important skill for Front for Front-End development','css3','blue');
INSERT INTO `skills`(`id`,`title`,`about`,`desc`,`name`,`color`) VALUES (10,'HTML5','HTML5 about','I''m acquainted with HTML5, I have been starting my Web Development way from it','html5','red');


INSERT INTO `skill_cards`(`icon`,`name`,`img`,`color`,`link`,`parent`) VALUES ('php','PHP','/images/php.png','blue','/skills/php','card_back');
INSERT INTO `skill_cards`(`icon`,`name`,`img`,`color`,`link`,`parent`) VALUES ('laravel','Laravel','/images/laravel.png','red','/skills/laravel','card_back');
INSERT INTO `skill_cards`(`icon`,`name`,`img`,`color`,`link`,`parent`) VALUES ('node','Node.js','/images/node.png','olive','/skills/node-js','card_back');
INSERT INTO `skill_cards`(`icon`,`name`,`img`,`color`,`link`,`parent`) VALUES ('database','MySql','/images/mysql.png','blue','/skills/database','card_back');
INSERT INTO `skill_cards`(`icon`,`name`,`img`,`color`,`link`,`parent`) VALUES ('docker','Docker','/images/docker.jpg','blue','/skills/docker','card_back');
INSERT INTO `skill_cards`(`icon`,`name`,`img`,`color`,`link`,`parent`) VALUES ('vuejs','Vue.js','/images/vuejs.jpg','green','/skills/vue-js','card_front');
INSERT INTO `skill_cards`(`icon`,`name`,`img`,`color`,`link`,`parent`) VALUES ('js','JavaScript','/images/js.png','yellow','/skills/js','card_front');
INSERT INTO `skill_cards`(`icon`,`name`,`img`,`color`,`link`,`parent`) VALUES ('webpack','Webpack','/images/webpack.png','blue','/skills/webpack','card_front');
INSERT INTO `skill_cards`(`icon`,`name`,`img`,`color`,`link`,`parent`) VALUES ('css3 alternate','CSS3','/images/css3.png','blue','/skills/css3','card_front');
INSERT INTO `skill_cards`(`icon`,`name`,`img`,`color`,`link`,`parent`) VALUES ('html5','HTML5','/images/html5.png','red','/skills/html5','card_front');

INSERT INTO `abouts`(`name`, `img`, `description`,`color`,`parent`) VALUES ('Vue.js','vuejs','I''m actively studying Vuex (actions, mutations, store, getters), Nuxt.js as Server Side Rendering, Vue-Cli, Vue, VueAxios, VueRouters and a lot of plugins for deploying','green','front');
INSERT INTO `abouts`(`name`, `img`, `description`,`color`,`parent`) VALUES ('Gulp.js','gulp','I''m usually using Gulp for individual front-end templates, it''s useful, when you want to synergize BrowserSync, SASS-compiler and etc.','red','front');
INSERT INTO `abouts`(`name`, `img`, `description`,`color`,`parent`) VALUES ('CSS3','css3 alternate','Obviously, it''s being the most important skill for Front for Front-End development','blue','front');
INSERT INTO `abouts`(`name`, `img`, `description`,`color`,`parent`) VALUES ('SASS/LESS/SCSS','sass','For me the most important is being always to use preprocessors for my code, it will increase code reading and get rid of the standard manipulations, for instance, with prefixes','pink','front');
INSERT INTO `abouts`(`name`, `img`, `description`,`color`,`parent`) VALUES ('HTML5','html5','I''m acquainted with HTML5, I have been starting my Web Development way from it','red','front');
INSERT INTO `abouts`(`name`, `img`, `description`,`color`,`parent`) VALUES ('JavaScript','js','I prefer to programming on native JavaScript for finding any solutions','yellow','front');
INSERT INTO `abouts`(`name`, `img`, `description`,`color`,`parent`) VALUES ('Webpack','webpack','It''s indeed conducive to use webpack plugin for total project compillation','blue','front');
INSERT INTO `abouts`(`name`, `img`, `description`,`color`,`parent`) VALUES ('PHP','php','I''m actively engaging in the PHP, also have an experience with Model-View-Controller modulation, PDO Connection, and more oriented on the Objective programming, interacted with standard patterns as ''Singleton'', ''Many to Many''','blue','back');
INSERT INTO `abouts`(`name`, `img`, `description`,`color`,`parent`) VALUES ('Laravel','laravel','Laravel is being sufficient wonderful framework for rapid projects building, essentially, working with php artisan is increasing your velocity potential. Like you can just create any migrations, model, view, collection, seed and so on','red','back');
INSERT INTO `abouts`(`name`, `img`, `description`,`color`,`parent`) VALUES ('MySql, PostgreSql','database','I''m acquainted with MySql stadard functions, migrations','green','back');
INSERT INTO `abouts`(`name`, `img`, `description`,`color`,`parent`) VALUES ('Docker','docker','I also prefer to deploy my projects via Docker compilitation, cause it''s making total process of installation indeed quickly and high productive, without any struggles','blue','back');
INSERT INTO `abouts`(`name`, `img`, `description`,`color`,`parent`) VALUES ('Node.js','node','I''m actively studying a Node.js, Express, MongoDb as Back End projects building','olive','back');
